# Generated by Django 4.2.8 on 2025-07-01 23:17

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristicResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(db_index=True, help_text='ID unique de la ressource (@id dans JSON-LD)', max_length=255, unique=True)),
                ('dc_identifier', models.CharField(db_index=True, help_text='Identifiant Dublin Core', max_length=255)),
                ('resource_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, help_text='Types de la ressource (@type dans JSON-LD)', size=None)),
                ('data', models.JSONField(default=dict, help_text='Données JSON-LD complètes')),
                ('name', models.JSONField(default=dict, help_text='Nom en plusieurs langues')),
                ('description', models.JSONField(default=dict, help_text='Description en plusieurs langues')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Coordonnées GPS', null=True, srid=4326)),
                ('address', models.JSONField(blank=True, default=dict, help_text='Adresse complète', null=True)),
                ('creation_date', models.DateField(blank=True, help_text='Date de création de la ressource', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date d'import dans la base")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Ressource active/visible')),
                ('available_languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), default=list, help_text='Langues disponibles pour cette ressource', size=None)),
            ],
            options={
                'verbose_name': 'Ressource touristique',
                'verbose_name_plural': 'Ressources touristiques',
                'db_table': 'touristic_resources',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource_types', 'is_active'], name='touristic_r_resourc_50670d_idx'), models.Index(fields=['creation_date'], name='touristic_r_creatio_1459fc_idx'), django.contrib.postgres.indexes.GinIndex(fields=['data'], name='data_gin_idx'), django.contrib.postgres.indexes.GinIndex(fields=['name'], name='name_gin_idx'), django.contrib.postgres.indexes.GinIndex(fields=['description'], name='description_gin_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('price_type', models.CharField(max_length=100)),
                ('description', models.JSONField(default=dict)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='tourism.touristicresource')),
            ],
            options={
                'verbose_name': 'Spécification de prix',
                'verbose_name_plural': 'Spécifications de prix',
                'db_table': 'price_specifications',
            },
        ),
        migrations.CreateModel(
            name='MediaRepresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('title', models.JSONField(default=dict)),
                ('mime_type', models.CharField(max_length=100)),
                ('is_main', models.BooleanField(default=False)),
                ('credits', models.CharField(blank=True, max_length=255)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='tourism.touristicresource')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
                'db_table': 'media_representations',
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('opens', models.TimeField()),
                ('closes', models.TimeField()),
                ('valid_from', models.DateField()),
                ('valid_through', models.DateField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='tourism.touristicresource')),
            ],
            options={
                'verbose_name': "Horaire d'ouverture",
                'verbose_name_plural': "Horaires d'ouverture",
                'db_table': 'opening_hours',
                'ordering': ['day_of_week', 'opens'],
                'indexes': [models.Index(fields=['resource', 'valid_from', 'valid_through'], name='opening_hou_resourc_3748d0_idx')],
            },
        ),
    ]
