# Chromatic configuration for DataTourisme UI components
# https://www.chromatic.com/docs/configuration

# Project settings
projectToken: $CHROMATIC_PROJECT_TOKEN
buildScriptName: build

# Visual testing settings
threshold: 0.2  # 20% change threshold for visual differences
diffThreshold: 0.05  # 5% difference threshold to trigger review

# Snapshot settings
diffIncludeAntiAliasing: true
pauseAnimationsAtEnd: true
delay: 300  # Wait 300ms before taking screenshots

# Test settings
exitZeroOnChanges: false  # Fail build on visual changes (CI mode)
exitOnceUploaded: false   # Continue running after upload
ignoreLastBuildOnBranch: main  # Ignore last build on main branch

# Browser settings
browsers:
  - name: chrome
    versions: [latest]
  - name: firefox
    versions: [latest]
  - name: safari
    versions: [latest]

# Viewport settings
viewports:
  - name: mobile
    width: 375
    height: 667
  - name: tablet
    width: 768
    height: 1024
  - name: desktop
    width: 1440
    height: 900
  - name: wide
    width: 1920
    height: 1080

# File patterns to ignore
ignorePatterns:
  - "**/*.test.tsx"
  - "**/*.spec.tsx"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"

# Parallel testing
parallelism: 4

# Turbosnap settings (for faster builds)
turbosnap: true
onlyChanged: true  # Only test changed stories

# Interaction testing
interactionTests: true
interactionTestsTimeout: 30000  # 30 second timeout

# Accessibility testing
a11y: true
a11yTimeout: 10000  # 10 second timeout for a11y tests

# Performance monitoring
performance: true
performanceTimeout: 30000  # 30 second timeout for performance tests

# Notification settings
notifications:
  email: true
  slack: false
  github: true

# Branch settings
branches:
  - main
  - develop
  - "feature/*"
  - "fix/*"
  - "hotfix/*"

# Auto-accept settings
autoAcceptChanges: false  # Require manual approval for changes
autoAcceptOnBranch: 
  - main  # Auto-accept on main branch (for releases)

# Storybook settings
storybookBuildDir: storybook-static
storybookConfigDir: .storybook

# Upload settings
uploadBuildDir: storybook-static
uploadTimeout: 600000  # 10 minute timeout for uploads

# Debug settings
debug: false
verbose: false

# Custom options
customOptions:
  # Mark stories as ready for visual testing
  readySelector: '[data-chromatic="ready"]'
  
  # Disable animations for consistent snapshots
  disableAnimations: true
  
  # Force color scheme
  forcedColors: none
  
  # Skip stories with specific tags
  skipTags: 
    - "skip-visual-tests"
    - "no-snapshot"